# Generated by Django 3.1.7 on 2021-04-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='task_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
