# Generated by Django 3.1.7 on 2021-04-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20210405_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Moderate', 'Moderate'), ('Low', 'Low')], default='Moderate', max_length=10),
        ),
    ]
