# Generated by Django 3.1.7 on 2021-04-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20210405_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='deadline',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
