# Generated by Django 3.1.7 on 2021-04-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_auto_20210405_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='task',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='task_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
