# Generated by Django 3.1.7 on 2021-04-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_auto_20210406_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='task',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='task_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
